### ISSUE TITLE
Sentence jobs not finishing at end of iter

### ISSUE THREAD

**Issue by coryshain** [tmills/uhhmm#47] opened 2017-01-10 04:26 UTC
I pulled today and I'm suddenly getting a bug on my system where the submitSentenceJobs call on line 304 of uhhmm.py hangs once all the sentence jobs have completed in the first iteration, and the models aren't resampled. This is especially strange because basically the same methods are being used by WorkDistributorServer.py to process compile jobs (which terminate as expected) and sentence jobs (which don't). For the sentence jobs, the ventilator chugs through the whole job queue and sends its b'0' signal to the socket at the end of the iteration, but for some reason control never returns to the uhhmm.py script. Any thoughts as to why this might be?

**Comment by tmills** [comment] 2017-01-10 11:22
No, but I've been looking into it. I hadn't noticed but Bill's been having
the same behavior. I then was able to repro but haven't gotten to the
bottom of it yet. Thanks for the confirmation.
Tim

**Comment by coryshain** [comment] 2017-01-10 11:40
Thanks, Tim. Looks like this is only happening in the GPU version. I'll keep digging on my end, too.

**Comment by tmills** [comment] 2017-01-10 11:59
I just merged an update that processes multiple sentences in batches on the gpu -- probably the cause. Can you try setting gpu_batch_size=1 in the .ini file and see if that works around it? Maybe there is an issue with the way it finishes the iteration when the sentences remaining is not the same as the batch size?
cc: @authorofnaught

**Comment by authorofnaught** [comment] 2017-01-10 13:24
So far so good for me.  Made it past the first iteration with the new pull
and gpu_batch_size=1.  I'll keep an eye on it.
Thanks!

**Comment by coryshain** [comment] 2017-01-10 13:27
Me too. gpu_batch_size=1 fixes the problem for me in the GPU version.

**Comment by tmills** [comment] 2017-01-10 13:47
Ok ill see if I can track down the issue with batch sizes, i have an idea
where it could be, would be nice to get those speed gains back.

**Comment by tmills** [comment] 2017-01-10 14:52
I added some debugging statements to the batch size code in PyzmqWorker.pyx. If either of you have a chance to try it (with gpu_batch_size=32) let me know what the output looks like where it hangs. I'm wondering if we'll see something like the following; or with the hang somewhere in the middle of that.

``INFO:root:Batch size 25 doesn't match power of 2 -- breaking into sub-batches
INFO:root:Processing mini-batch of size 16
INFO:root:Processing mini-batch of size 8
INFO:root:Processing mini-batch of size 1
INFO:root:After chopping up final batch, we have 25 samples processed.
``

**Comment by authorofnaught** [comment] 2017-01-10 15:42
Didn't see any output like that for gpu_batch_size=32, or for other values
of gpu_batch_size.  Here's some other things I noticed FWIW:

gpu_batch_size=1
No freeze after 200+ iterations.
Worker 0 returns sentences.

gpu_batch_size=2
Freeze after first iteration.
Worker 0 does not return sentences.
Thrust error thrown between sents 400 and 500:

terminate called after throwing an instance of
'thrust::system::system_error'

  what():  invalid argument

gpu_batch_size=16
Freeze after first iteration.
Worker 0 does not return sentences.
Thrust error thrown between sents 500 and 600. (same error as above)

gpu_batch_size=32
Freeze after first iteration.
Worker 0 does not return sentences.
No thrust error thrown.

**Comment by tmills** [comment] 2017-01-10 15:51
Hmm.... wonder if this has to do with cusplibrary version? At one point during my development of this change Lifeng told me I needed to do a pull. Can you try pulling from cusplibrary and copy over to wherever nvcc looks it up and then rebuild everything?

**Comment by authorofnaught** [comment] 2017-01-10 16:52
Ok.  That's done something positive.  With gpu_batch_size=32, I got past
the first iteration and worker 0 returned sentences.  I'll keep an eye on
it.
Thanks!

**Comment by tmills** [comment] 2017-01-11 19:16
@coryshain were you able to try this?

**Comment by authorofnaught** [comment] 2017-01-12 17:53
I did see this behavior again after 1919 iterations on 5-5-30-1
gpu_batch_size=32.

Same thrust error was output.
Worker 0 stopped returning sents.
Froze just before the end of the iteration.

I was able to restart successfully using the output dir.

**Comment by coryshain** [comment] 2017-01-13 02:34
Sorry for the delay, Tim. With the most recent version I still don't get past iteration 1 with any GPU batch size that I've tried but 1, regardless of whether I use powers of 2 or not. So far, I haven't seen any of the debugging statements you mentioned. I'm not sure why Bill has been able to avoid hanging on some batch sizes > 1.

**Comment by coryshain** [comment] 2017-01-13 03:13
(Sheepishly:) I'd been running these jobs on a departmental server, so I decided to try on my own laptop (which has a CUDA-capable GPU) and discovered that things were working fine at all batch sizes I tried (1, 2, 3, 17, and 32). The git repo on the server was current, but just in case I did a clean rebuild, and voila, things work fine at various batch sizes there, too, now. Seems like something wasn't rebuilt in the server repo when it should have been for some reason.  Maybe this will also be the solution to the other bug I recently opened (sampling state 0 at the wrong timestep). In any case, I'm very sorry for not catching this earlier, and I appreciate both of your suggestions and code tweaks. As far as I'm concerned, this issue is closed, but it sounds like Bill it still having trouble so I'll let him close it when appropriate.

**Comment by authorofnaught** [comment] 2017-01-13 16:22
Hi all.  Yeah, I did get the bug again, but it was so late in the running
that, in practice, it doesn't seem to be an issue for our (at least my)
purposes right now.  A thrust error after 1900 iters is a small price.  I'd
consider the issue closed as well - you know, unless it becomes an issue
again :)
Bill

**Comment by tmills** [comment] 2017-01-13 16:24
Yeah, it unfortunately still seems to be there but much rarer. I can put a
debug statement before every thrust call but that makes for very huge log
files and still takes over a day to find probably. Let's leave it open and
I'll come back to it once the sprint is finished.

**Closed as completed** 2017-12-08 19:36 UTC
